# Site settings
title: "~/Adi"
description: "Thoughts & Musings"
baseurl: "/blog"
url: ""
author: "Adi Mukherjee"
email: hi@adimin.net

# Build settings
kramdown:
    input: GFM
permalink: /blog/:title/

# Third-party services
# just leave empty to disable it
google_analytics:
disqus_shortname: 

plugins:
  - jekyll-sitemap
  - jemoji
  - tagging
  - jekyll-tagging-related_posts

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
