# Site settings
title: "~/Adi"
description: "Notes on stuff"
baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank
url: ""
author: "Adi Mukherjee"
email: hi@adimin.net

# Build settings
kramdown:
    input: GFM
permalink: /blog/:title/ 

plugins:
  - jekyll-sitemap
  - jemoji
  - tagging
  - jekyll-tagging-related_posts

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]
